"""empty message

Revision ID: 03361e78e1d5
Revises: 62bd2f0282e1
Create Date: 2020-04-20 11:58:56.853595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03361e78e1d5'
down_revision = '62bd2f0282e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
