"""empty message

Revision ID: 2d4db61c2306
Revises: de88260ed2f7
Create Date: 2020-04-20 12:12:12.634231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4db61c2306'
down_revision = 'de88260ed2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    # ### end Alembic commands ###
