"""empty message

Revision ID: 738fefcce8de
Revises: f6012fd3177f
Create Date: 2020-04-21 11:19:37.833485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738fefcce8de'
down_revision = 'f6012fd3177f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
